#FROM python:3.12-slim-bookworm
FROM python:3.11-bookworm

RUN apt-get update

# 한국어 처리 시 폰트 필요
RUN apt-get -y install fonts-nanum

# Timezone: KST 설정
RUN ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# Chromium
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && groupadd -r pptruser && useradd -rm -g pptruser -G audio,video pptruser

USER pptruser

WORKDIR /home/pptruser
COPY . /home/pptruser

RUN pip3 install -r requirements.txt

CMD ["python3", "chromium-api.py"]
